# Generated by Django 4.1.4 on 2022-12-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imageboard_remove_board_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='image',
            field=models.ImageField(default=1, upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ImageBoard',
        ),
    ]
