# Generated by Django 4.1.4 on 2022-12-08 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_card_deadline_alter_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='column_boards', to='api.board'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BoardColumn',
        ),
    ]
