# Generated by Django 4.1.4 on 2022-12-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_markcard_card_alter_markcard_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='column',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.column'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ColumnCard',
        ),
    ]
