# Generated by Django 4.1.4 on 2022-12-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_favourboards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavourBoards',
            new_name='FavouriteBoards',
        ),
        migrations.DeleteModel(
            name='FavoriteBoard',
        ),
    ]
